Models/Entities/Concretes/Article.cs
 using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace WebProject.Models.Entities.Concretes
{
    [Serializable]
    public class Article 
    {
        private int articleId;
        private int userId;
        private string articleName;
        private string author;
        private DateTime publishedDate;
        private DateTime updatedDate;
        private string articleContent;
         
        public Article() { }
        public Article(int articleId, int userId, string articleName, string author, DateTime publishedDate, DateTime updatedDate, string articleContent)
        {
            this.articleId = articleId;
            this.userId = userId;
            this.articleName = articleName;
            this.author = author;
            this.publishedDate = publishedDate;
            this.updatedDate = updatedDate;
            this.articleContent = articleContent;
        }

        public int ArticleId { get => articleId; set => articleId = value; }
        public int UserId { get => userId; set => userId = value; }
        public string ArticleName { get => articleName; set => articleName = value; }
        public string Author { get => author; set => author = value; }
        public DateTime PublishedDate { get => publishedDate; set => publishedDate = value; }
        public DateTime UpdatedDate { get => updatedDate; set => updatedDate = value; }
        public string ArticleContent { get => articleContent; set => articleContent = value; }
    }
}

Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProject.Models.DataAccess.Abstracts;
using WebProject.Models.DataAccess.Concretes;
using WebProject.Models.Entities.Concretes;
using WebProject.Models.Services.Abstracts;

namespace WebProject.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        [Route("get/article")]
        public Article getArticleNameById(int id)
        {
            return _articleService.GetArticleNameById(id);
        }

        [Route("get/all/articles")]
        public List<Article> getAllArticles()
        {
            return _articleService.GetAllArticles();
        }
        [Route("find/article")]
        public Article FindArticleByName(string name)
        {
            return _articleService.FindArticleByName(name);
        }
        [HttpPost]
        [Route("create/article")]
        public IActionResult CreateArticle(Article article)
        {
            _articleService.CreateArticle(article);
            return RedirectToAction("Dashboard", "Home");
        }
        
        [HttpGet]
        [Route("delete/article")]
        public void DeleteArticleById(int id)
        {
            _articleService.DeleteArticleById(id);
        }

        [HttpPost]
        [Route("update/article")]
        public IActionResult UpdateArticle(Article article)
        {
            _articleService.UpdateArticle(article);
            return RedirectToAction("Dashboard", "Home");
        }

        [HttpGet]
        [Route("get/all/articles/by/user")]
        public List<Article> GetAllArticlesByUser()
        {
            return _articleService.GetAllArticlesByUser();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebProject.Models;
using WebProject.Models.DataAccess.Concretes;
using WebProject.Models.Entities.Concretes;
using WebProject.Models.Services.Abstracts;

namespace WebProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
       

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Dashboard()
        {
            return View();
            
        }

        public IActionResult Article()
        {
            return View();
        }
        public IActionResult ArticleContent()
        {
            return View();
        }

        public IActionResult EditArticle()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProject.Models.Services.Abstracts;

namespace WebProject.Controllers
{
    public class LoginController : Controller
    {

        private readonly ILoginService _loginService;
        
        public LoginController(ILoginService loginService)
        {
            _loginService = loginService;
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
           bool result= _loginService.Login(username,password);
            if (result == true)
            {
                ViewData["session"] = "yes";
                return RedirectToAction("Dashboard", "Home");
            }
            else return RedirectToAction("Login", "Home");
        }

        public IActionResult LogOut()
        {
            _loginService.LogOut();
            return RedirectToAction("Login", "Home");

        }
             
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProject.Models.Entities.Concretes;
using WebProject.Models.Services.Abstracts;

namespace WebProject.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            _userService.Register(user);
            return RedirectToAction("Login", "Home");
        }
    }

}

Views/Home/Article.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model WebProject.Models.Entities.Concretes.Article
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/ckeditor/ckeditor.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <div class="container pt-3">

        <form asp-controller="Article" asp-action="CreateArticle" method="post" class="container">
            <div class="justify-content-end text-right">
                <button id="publish" type="submit" class="btn btn-success btn-lg pr-2">Publish</button>
            </div>

            <div class=" col-lg-10 d-flex mb-4">
                <i class="fas fa-plus-circle text-center fa-2x m-2" style="color: #BDC3C7"></i>
                <input  type="text" placeholder="Article Title..." class="form-control p-3" asp-for="ArticleName" id="ArticleName" required />
            </div>

            <div class=" col-lg-10 d-flex mt-4">
                <i class="fas fa-plus-circle text-center fa-2x m-2" style="color: #BDC3C7"></i>
                <textarea rows="50" cols="50" class="form-control ckeditor" placeholder="Article Content..." asp-for="ArticleContent"  id="ArticleContent" required></textarea>
            </div>

        </form>
    </div>

    <script>
        $(document).ready(function () {
            CKEDITOR.replace('#ArticleContent');
            CKEDITOR.config.width = "100%";
            CKEDITOR.config.height = "450px";
        });
    </script>
   

Views/Home/ArticleContent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;300&display=swap" rel="stylesheet">
<style>
    body {
        background-image: url("https://images.unsplash.com/photo-1542435503-956c469947f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        height:auto;
    }
    #fdiv {
        
    }

</style>
<div class="col-lg-10 container" id="fdiv"  style="padding-top:3%;">
    <div class="container">
        <h3 class="text-center p-3" id="title"></h3>
        <p  id="contentVal" style="font-family: 'Raleway', sans-serif; font-weight:bold;color:black; background-color: white;padding:50px;" class=""></p>
    </div>
    </div>

    <script>
        document.getElementById("title").innerHTML = localStorage.getItem("title");
        document.getElementById("contentVal").innerHTML = localStorage.getItem("content");

    </script>

Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<body>
    <div class="container">
        <div class="p-4 d-flex justify-content-center">
            <form class="d-flex col-lg-10 ">
                <input type="text" placeholder="Search.." name="search" class=" col-lg-8  ">
                <button type="submit" class="btn btn-secondary col-lg-1 "><i class="fa fa-search "></i></button>
            </form>
            <button type="submit" class="btn btn-secondary col-lg-2 text-center pl-2" style="text-decoration:none" onclick="location.href='@Url.Action("Article", "Home")'">
                Add Article <i class="fas fa-plus-circle fa-2x"></i>
            </button>
        </div>


        <table class="table table-striped" id="table">

            <thead>
                <tr>
                    
                    <th scope="col">Article Name</th>
                    <th scope="col">Author</th>
                    <th scope="col">Published Date</th>
                    <th scope="col">Updated Date</th>
                    <th scope="col">Read</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>

                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>


</body>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script>
    window.onload = function () {
        $.ajax({
            url: "https://localhost:44329/get/all/articles/by/user",
            type: 'GET',
            success: function (res) {
                let table = document.getElementById("table");
                if (res.length != 0) {

                }
                for (let i = 0; i < res.length; i++) {
                    let row = table.insertRow(i + 1);
                    let cell0 = row.insertCell(0);
                    let cell1 = row.insertCell(1);
                    let cell2 = row.insertCell(2); 9
                    let cell3 = row.insertCell(3);
                    let cell4 = row.insertCell(4);
                    let cell5 = row.insertCell(5);
                    let cell6 = row.insertCell(6);
                    let content = res[i].articleContent;
                    cell0.innerHTML = res[i].articleName;
                    cell1.innerHTML = res[i].author;
                    cell2.innerHTML = res[i].publishedDate;
                    cell3.innerHTML = res[i].updatedDate;
                    cell4.innerHTML = '<button id="btnread' + res[i].articleId + '"' + 'type="button" class="btn btn-success" onclick="read(' + res[i].articleId + ')" >Read</button>';
                    cell5.innerHTML = '<button id="btnread' + res[i].articleId + '"' + 'type="button" class="btn btn-success" onclick="updateArticle(' + res[i].articleId + ')" >Edit</button>';
                    cell6.innerHTML = '<button id="btnread' + res[i].articleId + '"' + 'type="button" class="btn btn-danger" onclick="deleteArticle(' + res[i].articleId + ')" >Delete</button>';
                }
            }
        });
    }

    function read(id) {
        $.ajax({
            url: "https://localhost:44329/get/article",
            type: "GET",
            data: { id: id},
            success: function (response) {
                localStorage.setItem("title", String(response.articleName))
                localStorage.setItem("content", String(response.articleContent));
                window.location.replace("https://localhost:44329/Home/ArticleContent");
            },
            error: function (data, status) {
                console.log(data + " " + status)
            }
        });
    }

    function deleteArticle(id) {
        $.ajax({
            url: "https://localhost:44329/delete/article",
            type: "GET",
            data: { id: id },
            success: function (response) {
                location.reload();
            },
            error: function (data, status) {
                console.log(data + " " + status)
            }
        });
    }

    function updateArticle(id) {
        $.ajax({
            url: "https://localhost:44329/get/article",
            type: "GET",
            data: { id: id },
            success: function (response) {
                localStorage.setItem("title", String(response.articleName));
                localStorage.setItem("content", String(response.articleContent));
                localStorage.setItem("articleId", String(response.articleId));
                window.location.replace("https://localhost:44329/Home/EditArticle");
            },
            error: function (data, status) {
                console.log(data + " " + status)
            }
        });
    }
</script>

Views/Home/EditArticle.cshtml
@{
    ViewData["Title"] = "Edit Page";
}

@model WebProject.Models.Entities.Concretes.Article
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

<div class="container pt-3">

    <form asp-controller="Article" asp-action="UpdateArticle" method="post" class="container">
        <div class="justify-content-end text-right">
            <button id="publish" type="submit" class="btn btn-success btn-lg">Save</button>
        </div>
        <input type="text" placeholder="Article Title..." class="form-control p-3" style="visibility:hidden" asp-for="ArticleId" id="ArticleId" required />
        <div class=" col-lg-10 d-flex mb-4">
            <i class="fas fa-plus-circle text-center fa-2x m-2" style="color: #BDC3C7"></i>
            <input type="text" placeholder="Article Title..." class="form-control p-3" asp-for="ArticleName" id="ArticleName" required />
        </div>

        <div class=" col-lg-10 d-flex mt-4">
            <i class="fas fa-plus-circle text-center fa-2x m-2" style="color: #BDC3C7"></i>
            <textarea rows="50" cols="50" class="form-control ckeditor" placeholder="Article Content..." asp-for="ArticleContent" id="ArticleContent" required></textarea>
        </div>

    </form>
</div>

<script>
        $(document).ready(function () {
            CKEDITOR.replace('#ArticleContent');
            CKEDITOR.config.width = "100%";
            CKEDITOR.config.height = "450px";
        });
        document.getElementById("ArticleId").value = localStorage.getItem("articleId");
        document.getElementById("ArticleName").value= localStorage.getItem("title");
        document.getElementById("ArticleContent").innerHTML = localStorage.getItem("content");
</script>

Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style>

    body {
        background-image: url('https://images.unsplash.com/photo-1549321495-305eb13f8aa9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>

<body>
    <div class="container" style="padding-top:10%">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="login-wrap p-0">
                    <h3 class="mb-5 text-center">Login to Your Account!</h3>
                    <form class="signin-form" method="post" id="loginForm" action="@Url.Action("Login", "Login")">
                        <div class="form-group pb-2">
                            <input id="username-field" name="username" type="text" class="form-control rounded-pill py-4" placeholder="Username" required>
                        </div>
                        <div class="form-group pb-2">
                            <input id="password-field" name="password" type="password" class="form-control rounded-pill py-4" placeholder="Password" required>
                        </div>

                        <div class="form-group pb-2">
                            <button style="background-color: #AED6F1" type="submit" class="form-control   rounded-pill text-center" id="submit-btn">Sign In</button>
                        </div>
                    </form>
                    <div class="form-group d-md-flex">
                        <div class="w-50">
                            <label class="checkbox-wrap checkbox-primary">
                                Remember Me
                                <input type="checkbox" checked>
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="w-50 text-md-right">
                            <a href="#" style="color: #fff">Forgot Password</a>
                        </div>
                    </div>

                    <p class="w-100 text-center font-weight-bold text-light ">&mdash; Create Account or Sign in With &mdash;</p>
                    <div class="social d-flex text-center">
                        <a href="@Url.Action("Register", "Home")" class="px-5 py-2 mr-md-1 rounded bg-light text-dark font-weight-bold" style="text-decoration:none">Sign Up</a>
                        <a href="#" class="px-5 py-2 ml-md-1 rounded bg-light text-dark font-weight-bold" style="text-decoration:none">Google</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    

Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Login";
}
@model WebProject.Models.Entities.Concretes.User
<style>
    body {
        background-image: url("https://images.unsplash.com/photo-1549321495-305eb13f8aa9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }

    .input-bg {
        background-color: #F0F2F3;
    }
</style>

<body>
    <div class="container" style="margin-top:10%">
        <div style="background-color:transparent">
            <div class="col-10 align-middle bg-light">
                <form asp-controller="User" asp-action="Register" class="container align-content-center col-lg-8 p-5" method="post">
                    <h3 class="text-center">Registration Form</h3>
                    <div class="form-group  p-2">
                        <input type="text" placeholder="Name and Surname" asp-for="FullName" class="form-control  border-dark radius rounded-pill border-0 input-bg" required>
                    </div>
                    <div class="form-group p-2">
                        <input type="text" placeholder="Username" asp-for="Username" class="form-control border-dark rounded-pill border-0 input-bg" required >
                    </div>
                    <div class="form-group p-2">
                        <input type="password" placeholder="Password" asp-for="Password" class="form-control border-dark rounded-pill border-0 input-bg" required>
                    </div>
                    <div class="form-group p-2">
                        <input type="text" placeholder="Email Address" asp-for="Email" class="form-control border-dark rounded-pill border-0 input-bg" required >
                    </div>
                    <div class="form-group p-2">
                        <input type="text" placeholder="Birth Year" asp-for="BirthYear" class="form-control border-dark rounded-pill border-0 input-bg" required>
                    </div>

                    <button type="submit" class="btn btn-primary btn-lg form-control p-2">Create Account</button>
                </form>

            </div>
        </div>
    </div>
</body>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>